name: Build ConSite APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Cordova
        run: npm install -g cordova

      - name: Adicionar Plataforma Android
        run: cordova platform add android

      - name: Gerar APK Android
        run: cordova build android --verbose

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: ConSite-APK
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
